services:
  - type: web
    name: sistema-agendamento-caronas
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && python manage.py criar_dados_demo && gunicorn caronas.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SECRET_KEY
        generateValue: true
