services:
  - type: web
    name: sistema-agendamento-caronas
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && python manage.py criar_dados_demo && gunicorn caronas.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: POSTGRES_DB
        fromDatabase:
          name: caronas-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: caronas-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: caronas-postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: caronas-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: caronas-postgres
          property: port

databases:
  - name: caronas-postgres
    databaseName: caronas_db
    user: caronas_user
