# Generated by Django 6.0.5 on 2026-05-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=180)),
                ('cidade', models.CharField(default='Lavras', max_length=80)),
                ('ponto_referencia', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
                'ordering': ['cidade', 'nome'],
                'unique_together': {('nome', 'cidade')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('PASSAGEIRO', 'Passageiro'), ('MOTORISTA', 'Motorista'), ('AMBOS', 'Passageiro e motorista')], default='PASSAGEIRO', max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=20, verbose_name='matricula')),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfis de usuarios',
                'ordering': ['usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_saida', models.DateTimeField()),
                ('valor_por_vaga', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('vagas_disponiveis', models.PositiveSmallIntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caronas_destino', to='agendamentos.local')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caronas_origem', to='agendamentos.local')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caronas_oferecidas', to='agendamentos.perfilusuario')),
            ],
            options={
                'verbose_name': 'carona',
                'verbose_name_plural': 'caronas',
                'ordering': ['-data_hora_saida'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=160)),
                ('carona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='agendamentos.carona')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='agendamentos.perfilusuario')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-criado_em'],
                'unique_together': {('carona', 'passageiro')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='agendamentos.reserva')),
            ],
            options={
                'verbose_name': 'avaliacao',
                'verbose_name_plural': 'avaliacoes',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=80)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('cor', models.CharField(max_length=30)),
                ('capacidade', models.PositiveSmallIntegerField(default=4)),
                ('ativo', models.BooleanField(default=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='agendamentos.perfilusuario')),
            ],
            options={
                'verbose_name': 'veiculo',
                'verbose_name_plural': 'veiculos',
                'ordering': ['modelo', 'placa'],
            },
        ),
        migrations.AddField(
            model_name='carona',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caronas', to='agendamentos.veiculo'),
        ),
    ]
